# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b6c649ca3a51f695b390ab5cf7a1deef33b91550ddb2ecb40d18a8d0468e73bc51a263d38a66bdc1a903e5ff0debacceec29766353bb0abb4bef9adc15c1946

test:
  secret_key_base: e65bbae9c430c461f3e16c9bec4020c5d57f22d3348ac0c87ea4521086b6360cb8a5311be3fb864906a1aa12a6193dfbdde67892eb669601d3720f17645c2745

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
